default: &default
  sitename: ""
  title: "atart"
  domain: ""
  description: ""

  sms_pid: ""
  sms_number: ""
  sms_extend: ""
  sms_password: ""
  qq_connect_appid: "101106307"
  qq_connect_appkey: "975f8d8c239db386003163269962e95f"


production:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
