require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FundRaiseSupportsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FundRaiseSupport. As you add validations to FundRaiseSupport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FundRaiseSupportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all fund_raise_supports as @fund_raise_supports" do
      fund_raise_support = FundRaiseSupport.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:fund_raise_supports)).to eq([fund_raise_support])
    end
  end

  describe "GET #show" do
    it "assigns the requested fund_raise_support as @fund_raise_support" do
      fund_raise_support = FundRaiseSupport.create! valid_attributes
      get :show, {:id => fund_raise_support.to_param}, valid_session
      expect(assigns(:fund_raise_support)).to eq(fund_raise_support)
    end
  end

  describe "GET #new" do
    it "assigns a new fund_raise_support as @fund_raise_support" do
      get :new, {}, valid_session
      expect(assigns(:fund_raise_support)).to be_a_new(FundRaiseSupport)
    end
  end

  describe "GET #edit" do
    it "assigns the requested fund_raise_support as @fund_raise_support" do
      fund_raise_support = FundRaiseSupport.create! valid_attributes
      get :edit, {:id => fund_raise_support.to_param}, valid_session
      expect(assigns(:fund_raise_support)).to eq(fund_raise_support)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FundRaiseSupport" do
        expect {
          post :create, {:fund_raise_support => valid_attributes}, valid_session
        }.to change(FundRaiseSupport, :count).by(1)
      end

      it "assigns a newly created fund_raise_support as @fund_raise_support" do
        post :create, {:fund_raise_support => valid_attributes}, valid_session
        expect(assigns(:fund_raise_support)).to be_a(FundRaiseSupport)
        expect(assigns(:fund_raise_support)).to be_persisted
      end

      it "redirects to the created fund_raise_support" do
        post :create, {:fund_raise_support => valid_attributes}, valid_session
        expect(response).to redirect_to(FundRaiseSupport.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved fund_raise_support as @fund_raise_support" do
        post :create, {:fund_raise_support => invalid_attributes}, valid_session
        expect(assigns(:fund_raise_support)).to be_a_new(FundRaiseSupport)
      end

      it "re-renders the 'new' template" do
        post :create, {:fund_raise_support => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fund_raise_support" do
        fund_raise_support = FundRaiseSupport.create! valid_attributes
        put :update, {:id => fund_raise_support.to_param, :fund_raise_support => new_attributes}, valid_session
        fund_raise_support.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested fund_raise_support as @fund_raise_support" do
        fund_raise_support = FundRaiseSupport.create! valid_attributes
        put :update, {:id => fund_raise_support.to_param, :fund_raise_support => valid_attributes}, valid_session
        expect(assigns(:fund_raise_support)).to eq(fund_raise_support)
      end

      it "redirects to the fund_raise_support" do
        fund_raise_support = FundRaiseSupport.create! valid_attributes
        put :update, {:id => fund_raise_support.to_param, :fund_raise_support => valid_attributes}, valid_session
        expect(response).to redirect_to(fund_raise_support)
      end
    end

    context "with invalid params" do
      it "assigns the fund_raise_support as @fund_raise_support" do
        fund_raise_support = FundRaiseSupport.create! valid_attributes
        put :update, {:id => fund_raise_support.to_param, :fund_raise_support => invalid_attributes}, valid_session
        expect(assigns(:fund_raise_support)).to eq(fund_raise_support)
      end

      it "re-renders the 'edit' template" do
        fund_raise_support = FundRaiseSupport.create! valid_attributes
        put :update, {:id => fund_raise_support.to_param, :fund_raise_support => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested fund_raise_support" do
      fund_raise_support = FundRaiseSupport.create! valid_attributes
      expect {
        delete :destroy, {:id => fund_raise_support.to_param}, valid_session
      }.to change(FundRaiseSupport, :count).by(-1)
    end

    it "redirects to the fund_raise_supports list" do
      fund_raise_support = FundRaiseSupport.create! valid_attributes
      delete :destroy, {:id => fund_raise_support.to_param}, valid_session
      expect(response).to redirect_to(fund_raise_supports_url)
    end
  end

end
